version: "3.8"

services:
  app: 
    image: httpd:latest
    restart: always
    env_file:
      - stack.env
    environment:
      WAIT_HOSTS: swarm01
      IMAGE_NAME: ${IMAGE_NAME}
      IMAGE_TEST_NEW_VALUE: ${IMAGE_TEST_NEW_VALUE}
    deploy:
      placement:
        constraints:
          - node.role == worker