version: "3.8"

services:
  app: 
    image: httpd:lastest
    restart: always
    environment:
      WAIT_HOSTS: swarm01
    deploy:
      placement:
        constraints:
          - node.role == worker