version: "3.8"

services:
  app: 
    image: httpd:latest
    restart: always
    environment:
      WAIT_HOSTS: swarm01
      IMAGE_NAME: ${IMAGE_NAME}
    deploy:
      placement:
        constraints:
          - node.role == worker